export const MOVIES_LIST_REQUEST = "MOVIES_LIST_REQUEST";
export const MOVIES_LIST_SUCCESS = "MOVIES_LIST_SUCCESS";
export const MOVIES_LIST_FAIL = "MOVIES_LIST_FAIL";
export const MOVIES_LIST_RESET = "MOVIES_LIST_RESET";

export const MOVIES_RANDOM_REQUEST = "MOVIES_RANDOM_REQUEST";
export const MOVIES_RANDOM_SUCCESS = "MOVIES_RANDOM_SUCCESS";
export const MOVIES_RANDOM_FAIL = "MOVIES_RANDOM_FAIL";

export const MOVIE_DETAILS_REQUEST = "MOVIE_DETAILS_REQUEST";
export const MOVIE_DETAILS_SUCCESS = "MOVIE_DETAILS_SUCCESS";
export const MOVIE_DETAILS_FAIL = "MOVIE_DETAILS_FAIL";
export const MOVIE_DETAILS_RESET = "MOVIE_DETAILS_RESET";

export const MOVIE_TOP_RATED_REQUEST = "MOVIE_TOP_RATED_REQUEST";
export const MOVIE_TOP_RATED_SUCCESS = "MOVIE_TOP_RATED_SUCCESS";
export const MOVIE_TOP_RATED_FAIL = "MOVIE_TOP_RATED_FAIL";

export const CREATE_REVIEW_REQUEST = "CREATE_REVIEW_REQUEST";
export const CREATE_REVIEW_SUCCESS = "CREATE_REVIEW_SUCCESS";
export const CREATE_REVIEW_FAIL = "CREATE_REVIEW_FAIL";
export const CREATE_REVIEW_RESET = "CREATE_REVIEW_RESET";

export const DELETE_ALL_MOVIES_REQUEST = "DELETE_ALL_MOVIES_REQUEST";
export const DELETE_ALL_MOVIES_SUCCESS = "DELETE_ALL_MOVIES_SUCCESS";
export const DELETE_ALL_MOVIES_FAIL = "DELETE_ALL_MOVIES_FAIL";
export const DELETE_ALL_MOVIES_RESET = "DELETE_ALL_MOVIES_RESET";

export const DELETE_MOVIE_REQUEST = "DELETE_MOVIE_REQUEST";
export const DELETE_MOVIE_SUCCESS = "DELETE_MOVIE_SUCCESS";
export const DELETE_MOVIE_FAIL = "DELETE_MOVIE_FAIL";
export const DELETE_MOVIE_RESET = "DELETE_MOVIE_RESET";

export const UPDATE_MOVIE_REQUEST = "UPDATE_MOVIE_REQUEST";
export const UPDATE_MOVIE_SUCCESS = "UPDATE_MOVIE_SUCCESS";
export const UPDATE_MOVIE_FAIL = "UPDATE_MOVIE_FAIL";
export const UPDATE_MOVIE_RESET = "UPDATE_MOVIE_RESET";

export const UPDATE_SERIES_REQUEST = "UPDATE_SERIES_REQUEST";
export const UPDATE_SERIES_SUCCESS = "UPDATE_SERIES_SUCCESS";
export const UPDATE_SERIES_FAIL = "UPDATE_SERIES_FAIL";
export const UPDATE_SERIES_RESET = "UPDATE_SERIES_RESET";

export const CREATE_MOVIE_REQUEST = "CREATE_MOVIE_REQUEST";
export const CREATE_MOVIE_SUCCESS = "CREATE_MOVIE_SUCCESS";
export const CREATE_MOVIE_FAIL = "CREATE_MOVIE_FAIL";
export const CREATE_MOVIE_RESET = "CREATE_MOVIE_RESET";

export const CREATE_SERIES_REQUEST = "CREATE_SERIES_REQUEST";
export const CREATE_SERIES_SUCCESS = "CREATE_SERIES_SUCCESS";
export const CREATE_SERIES_FAIL = "CREATE_SERIES_FAIL";
export const CREATE_SERIES_RESET = "CREATE_SERIES_RESET";

export const ADD_CAST = "ADD_CAST";
export const EDIT_CAST = "EDIT_CAST";
export const DELETE_CAST = "DELETE_CAST";
export const RESET_CAST = "RESET_CAST";

// Constants cho phim chiếu rạp
export const MOVIES_CINEMA_REQUEST = "MOVIES_CINEMA_REQUEST";
export const MOVIES_CINEMA_SUCCESS = "MOVIES_CINEMA_SUCCESS";
export const MOVIES_CINEMA_FAIL = "MOVIES_CINEMA_FAIL";
export const MOVIES_CINEMA_RESET = "MOVIES_CINEMA_RESET";

// Constants cho phim lẻ
export const MOVIES_SINGLE_REQUEST = "MOVIES_SINGLE_REQUEST";
export const MOVIES_SINGLE_SUCCESS = "MOVIES_SINGLE_SUCCESS";
export const MOVIES_SINGLE_FAIL = "MOVIES_SINGLE_FAIL";
export const MOVIES_SINGLE_RESET = "MOVIES_SINGLE_RESET";

// Constants cho phim bộ
export const MOVIES_SERIES_REQUEST = "MOVIES_SERIES_REQUEST";
export const MOVIES_SERIES_SUCCESS = "MOVIES_SERIES_SUCCESS";
export const MOVIES_SERIES_FAIL = "MOVIES_SERIES_FAIL";
export const MOVIES_SERIES_RESET = "MOVIES_SERIES_RESET";

// Constants cho anime
export const MOVIES_ANIME_REQUEST = "MOVIES_ANIME_REQUEST";
export const MOVIES_ANIME_SUCCESS = "MOVIES_ANIME_SUCCESS";
export const MOVIES_ANIME_FAIL = "MOVIES_ANIME_FAIL";
export const MOVIES_ANIME_RESET = "MOVIES_ANIME_RESET";


export const HOME_PAGE_DATA_REQUEST = "HOME_PAGE_DATA_REQUEST";
export const HOME_PAGE_DATA_SUCCESS = "HOME_PAGE_DATA_SUCCESS";
export const HOME_PAGE_DATA_FAIL = "HOME_PAGE_DATA_FAIL";